/* ────────────────────────────────────────────────────────────────────────
   The mark, as data — generated by scripts/gen-logo-pixels.mjs from
   public/logo.svg. Don't hand-edit; edit the logo and re-run the script.

   The mark is a dithered disc on a 20×20 lattice: 314 cells of flat grey,
   3px apart, 2.5px each, inside a 64-unit box. Kept as data rather than as an
   <img> so the splash can animate cells individually — see
   components/logo-mark.
   ──────────────────────────────────────────────────────────────────────── */

/** Cells per side. */
export const GRID = 20;
/** Both axes of the source viewBox. */
export const VIEWBOX = 64;
/** Where the first cell starts, in viewBox units. */
export const ORIGIN = 2;
/** Centre-to-centre spacing, in viewBox units. */
export const PITCH = 3;
/** One cell's side, in viewBox units — a hair under the pitch, so the lattice
    keeps its 0.5 gap and the disc reads as pixels rather than as a fill. */
export const CELL = 2.5;

/** Level alphabet: index × 4 is the cell's grey, 0–252. */
const LEVELS =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/* One string per row, one character per cell — "." for the cells the circle
   clips away. The disc is legible here as its own silhouette, which is the
   point: this stays reviewable in a diff. */
const ROWS = [
  ".......UJUNZN.......",
  ".....LZQZQeVeVj.....",
  "....KVJVOaOaTfTfY...",
  "...MaRaRfWfWkbkbpg..",
  "..JUJUNZNZSeSdXiXi..",
  ".LZQZQeVeVjajaofnet.",
  ".VJVOaOaTfTfYkYkdpd.",
  "aRaRfWfWkbkbpgpgulul",
  "JUNZNZSeSdXiXicncnhs",
  "ZQeVeVjajaofnetjsjxo",
  "OaOaTfTfYkYkdpdpiuit",
  "fWfWkbkbpgpgululzqzq",
  "NZSeSdXiXicncnhshsmx",
  ".Vjajaofnetjsjxoxo2.",
  ".fTfYkYkdpdpiuitnyn.",
  "..kbpgpgululzqzq4v..",
  "..XiXicncnhshsmxmx..",
  "...fnetjsjxoxo2t2...",
  ".....pdpiuitnyn.....",
  ".......lzqzq4.......",
];

export type LogoCell = {
  /** Left edge, in viewBox units. */
  x: number;
  /** Top edge, in viewBox units. */
  y: number;
  /** The cell's grey, as ink opacity — see components/logo-mark for why the
      mark is drawn as one ink at varying opacity rather than as 77 greys. */
  opacity: number;
  /** Lattice position, for anything deriving motion from where a cell sits. */
  col: number;
  row: number;
};

/** Decoded once at module load. Server-only in practice: the splash that reads
    this renders on the server and ships as markup, not as data. */
export const LOGO_CELLS: readonly LogoCell[] = ROWS.flatMap((line, row) =>
  [...line].flatMap((char, col) => {
    const level = LEVELS.indexOf(char);
    if (level < 0) return [];
    return [
      {
        x: ORIGIN + col * PITCH,
        y: ORIGIN + row * PITCH,
        opacity: Number(((level * 4) / 255).toFixed(3)),
        col,
        row,
      },
    ];
  }),
);
